-- require("Comment").setup({
--     -- change the leader for line comment from gc to gC
--     toggler = {
--         line = "<leader>cC",   -- line comment toggle
--         block = "<leader>cB",  -- block comment toggle
--     },
--     -- change the operator-pending mappings from gc/gb to gC/gB
--     opleader = {
--         line = "<leader>cC",  
--         block = "<leader>cB",
--     },
--     -- optionally keep extra mappings like comment above/below
--     extra = {
--         above = "<leader>cO",
--         below = "<leader>co",
--         eol = "<leader>cA",
--     },
--     -- ignore empty lines if you want
--     ignore = "^$",
-- })
--



-- lua/plugins/comment.lua
-- local M = {}
--
-- function M.setup()
-- require("Comment").setup({
--     mappings = {
--         basic = false,       -- disables default gc/gcc mappings
--         extra = false,       -- disables gcO/gco/gcA mappings
--     },
--     toggler = {
--         line = "<leader>c",
--         block = "<leader>bc",
--     },
--     opleader = {
--         line = "<leader>c",
--         block = "<leader>bc",
--     },
-- })
-- end
--
-- -- call setup when required
-- M.setup()
--
-- return M
