-- vim.api.nvim_create_autocmd("BufWritePre", {
--     pattern = { "*.c", "*.h" },
--     callback = function()
--         local file = vim.fn.expand("%:p")
--
--         vim.fn.jobstart({ "c_formatter_42", file }, {
--             stdout_buffered = true,
--             stderr_buffered = true,
--             on_exit = function(_, exit_code)
--                 -- reload the file AFTER formatting is done
--                 vim.schedule(function()
--                     if exit_code == 0 then
--                         vim.cmd("silent edit")
--                         vim.notify("✅ Formatted with c_formatter_42", vim.log.levels.INFO)
--                     else
--                         vim.notify("❌ Format failed (maybe missing c_formatter_42?)", vim.log.levels.ERROR)
--                     end
--                 end)
--             end,
--         })
--     end,
-- })
